siteTitle = "Gaël Destrem"
siteDescr = "Fullstack Developer"
siteAuthor = "Gaël Destrem"

siteLinkedinUrl = "https://www.linkedin.com/in/gaeldestrem/"
siteGithubUrl = "https://github.com/gaeldestrem"
siteEmailUrl = "gael.destrem@gmail.com"

googleAnalyticsId = "UA-46743284-1"

linkPrefix = ""
